### ISSUE TITLE
Compiling the native code

### ISSUE THREAD

**Issue by JoelSjogren** [dbrant/mandelbrot-android#2]
Hello! I have made a small change to mandelbrot_wrap.c and it should affect the Mandelbrot picture but it doesn't. This probably means that Android Studio didn't recompile that file for me. What do I need to do to build the JNI part of this project? I did specify the NDK in File->Project Structure. Is it true that I need to install gradle-experimental?

**Comment by dbrant** [comment]
Hi there,
This project does not yet use the experimental JNI functionality built into Gradle. To build the native library, open a console to `app/src/main/jni`, and run `ndk-build` (The NDK needs to be in your PATH in order for this to work). It should automatically build the library and copy it to the `libs` directory.
